version: "3.2"

services:
  whirlpool:
    image: "samouraiwallet/dojo-whirlpool:${DOJO_WHIRLPOOL_VERSION_TAG}"
    container_name: whirlpool
    build:
      context: ./whirlpool
      args:
        WHIRLPOOL_LINUX_UID: ${WHIRLPOOL_LINUX_UID}
        WHIRLPOOL_LINUX_GID: ${WHIRLPOOL_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-whirlpool.conf
    restart: always
    command: /restart.sh
    expose:
      - "8898"
    volumes:
      - data-whirlpool:/home/whirlpool
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      whirlnet:
        ipv4_address: ${NET_WHIRL_WHIRLPOOL_IPV4}

volumes:
  data-whirlpool:
